### ISSUE TITLE
-b option can not be used

### ISSUE THREAD

**Issue by m3ng9i** [hasit/bolter#13]
In readme, there is:

    --bucket BUCKET, -b BUCKET  boltdb BUCKET to view

But when I run `bolter -h`, there is no description about `-b`:

```
$ bolter -h
NAME:
  bolter - view boltdb file interactively in your terminal

VERSION:
  2.0.0

USAGE:
  bolter [global options]

GLOBAL OPTIONS:
  --file FILE, -f FILE  boltdb FILE to view
  --help, -h            show help
  --version, -v         print the version
  
AUTHOR:
  Hasit Mistry <hasitnm@gmail.com>
COPYRIGHT:
  (c) 2016 Hasit Mistry
```

If I add a `-b` in the command, I got an error:
```
$ bolter -f /tmp/b.db -b data
Incorrect Usage. flag provided but not defined: -b
```

**Comment by hasit** [comment]
Hello @m3ng9i,

The README is a but outdated after the latest changes. Sorry about that. As of now, you can open a file with `bolter -f FILE` and then navigate through buckets interactively,

**Comment by m3ng9i** [comment]
I got it. Thanks.
